# Generated by Django 5.0.7 on 2024-12-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('Pending', '대기 중'), ('Approved', '승인됨'), ('Rejected', '거절됨')], default='Pending', max_length=20),
        ),
    ]
