# Generated by Django 5.0.7 on 2024-12-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rentalrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='daily_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='일 단위 비용'),
        ),
        migrations.AddField(
            model_name='item',
            name='weekly_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='주 단위 비용'),
        ),
    ]
